name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show tree
        run: |
          ls -lah
          echo 'Ready to deploy (server secrets required).'
