name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script_stop: true
          script: |
            set -e
            mkdir -p ${{ secrets.PROJECT_DIR }}
            cd ${{ secrets.PROJECT_DIR }}
            if [ -d .git ]; then
              git fetch --all --prune
              git reset --hard
              git checkout main || git checkout -b main
              git pull origin main
            else
              git clone --depth 1 https://github.com/${{ github.repository }} .
            fi
            if [ ! -z "${{ secrets.ENV_FILE }}" ]; then echo "${{ secrets.ENV_FILE }}" > .env; fi
            docker compose pull || true
            docker compose build --pull
            docker compose up -d
            sleep 5
            docker compose ps
